# Generated by Django 4.1.7 on 2023-05-16 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faultDetector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("description", models.CharField(max_length=45)),
                ("sourceUrl", models.CharField(max_length=256)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={"db_table": "Algorithm",},
        ),
        migrations.AddField(
            model_name="datasetmodel",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="datasetmodel",
            name="file",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="datasetmodel",
            name="name",
            field=models.CharField(max_length=45),
        ),
    ]
